In [1]:
!pip install numpy


In [2]:
### Numpy is a general purpose array-processing package. it provides a high performance multidimension array object

In [3]:
import numpy as np

In [6]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [7]:
type(arr)

numpy.ndarray

In [10]:
##### ## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
## check the shape of the array
arr.shape

(3, 5)

In [14]:
### check the shape of the array
arr.shape

(3, 5)

In [15]:
## indexing 

In [16]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [18]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [19]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [20]:
val=2
arr[arr<3]

array([1, 2, 2])

In [23]:
val=2
arr[arr<6]

array([1, 2, 3, 4, 5, 2, 3, 4, 5])

In [25]:
## Create arrays and reshape 

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
arr1=np.arange(0,10).reshape(2,5)

In [27]:
arr2=np.arange(0,10).reshape(2,5)

In [28]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [29]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
arr_ex=np.random.randn(4,4)

In [31]:
arr_ex

array([[-0.62575727,  1.06293322, -0.54581728,  0.66677814],
       [ 1.70909892,  1.47335674,  0.8573285 , -0.34979919],
       [-0.97299578,  1.93461856,  0.14162423, -3.10284863],
       [ 1.28068744,  0.9506203 ,  0.74975484, -1.53903389]])

In [33]:
!pip install seaborn

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)


In [34]:
import seaborn as sns

In [35]:
sns.displot(pd.DataFrame(arr_ex.reshape(16,1)))

NameError: name 'pd' is not defined

In [40]:
np.random.randint(0,100,8).reshape(4,2)

array([[90, 40],
       [74, 17],
       [49, 18],
       [59, 17]], dtype=int32)

In [43]:
np.random.random_sample((1,5))

array([[0.94466894, 0.65320496, 0.39800326, 0.6201977 , 0.05116231]])

In [ ]:
np.random.random_sample